#FROM gradle:7.6.1-jdk17-alpine as gradle_builder
#COPY --chown=gradle:gradle src/ /app/src
#COPY --chown=gradle:gradle build.gradle /app/build.gradle
#COPY --chown=gradle:gradle settings.gradle /app/settings.gradle
#WORKDIR /app
#RUN gradle bootJar --no-daemon
#RUN ls -la build/libs
#
#FROM eclipse-temurin:17.0.1_12-jre as builder
#WORKDIR extracted
#COPY --from=gradle_builder /app/build/libs/*.jar app.jar
#RUN java -Djarmode=layertools -jar app.jar extract
#
#FROM eclipse-temurin:17.0.1_12-jre
#WORKDIR application
#COPY --from=builder extracted/dependencies/ ./
#COPY --from=builder extracted/spring-boot-loader/ ./
#COPY --from=builder extracted/snapshot-dependencies/ ./
#COPY --from=builder extracted/application/ ./
#EXPOSE 8080
#ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]