from django.db import models
from djongo.models import Model

# Create your models here.

class Drone(Model):
    _id = models.CharField(max_length=255)
    chancout_RC_CHANNELS = models.IntegerField
    accel_cal_x_SENSOR_OFFSETS = models.CharField(max_length=255)
    django_migrations = models.CharField(max_length=255)
    mag_ofs_x_SENSOR_OFFSETS = models.IntegerField()
    yacc_RAW_IMU = models.IntegerField()
    vx_LOCAL_POSITION_NED = models.IntegerField()
    zgyro_RAW_IMU_predict = models.CharField(max_length=255)
    zacc_RAW_IMU_predict = models.CharField(max_length=255)
    xacc_RAW_IMU_predict = models.CharField(max_length=255)
    loginfo = models.CharField(max_length=255)
    ymag_RAW_IMU = models.IntegerField()
    x_LOCAL_POSITION_NED = models.IntegerField()
    yaw_ATTITUDE = models.CharField(max_length=255)
    servo8_raw_SERVO_OUTPUT_RAW = models.IntegerField()
    vibration_z_VIBRATION = models.CharField(max_length=255)
    nav_bearing_NAV_CONTROLLER_OUTPUT = models.IntegerField()
    chan12_raw_RC_CHANNELS = models.IntegerField()
    device_id = models.CharField(max_length=255)
    xmag_RAW_IMU = models.IntegerField()
    vy_GLOBAL_POSITION_INT = models.IntegerField()
    press_abs_SCALED_PRESSURE = models.CharField(max_length=255)
    chan15_raw_RC_CHANNELS = models.IntegerField()
    vibration_z_VIBRATION_predict = models.CharField(max_length=255)
    vibration_x_VIBRATION = models.CharField(max_length=255)
    server_response_timestamp = models.CharField(max_length=255)
    airspeed_VFR_HUD = models.IntegerField()
    flight_id = models.FloatField()
    ygyro_RAW_IMU_predict = models.CharField(max_length=255)
    port = models.CharField(max_length=255)
    voltages1_BATTERY_STATUS = models.IntegerField()
    vx_GLOBAL_POSITION_INT = models.IntegerField()
    xacc_RAW_IMU = models.IntegerField()
    status = models.CharField(max_length=255)
    zmag_RAW_IMU = models.IntegerField()
    yaw_ATTITUDE_predict = models.CharField(max_length=255)
    vibration_x_VIBRATION_predict = models.CharField(max_length=255)
    xgyro_RAW_IMU_predict = models.CharField(max_length=255)
    pitch_ATTITUDE_predict = models.CharField(max_length=255)
    vy_LOCAL_POSITION_NED = models.IntegerField()
    yacc_RAW_IMU_predict = models.CharField(max_length=255)
    Vservo_POWER_STATUS = models.IntegerField()
    chan14_raw_RC_CHANNELS = models.IntegerField()
    groundspeed_VFR_HUD = models.CharField(max_length=255)
    data_id = models.CharField(max_length=255)
    mag_ofs_y_SENSOR_OFFSETS = models.IntegerField()
    roll_ATTITUDE = models.CharField(max_length=255)
    zacc_RAW_IMU = models.CharField(max_length=255)
    vibration_y_VIBRATION_predict = models.CharField(max_length=255)
    zmag_RAW_IMU_predict = models.CharField(max_length=255)
    ymag_RAW_IMU_predict = models.CharField(max_length=255)
    pitch_ATTITUDE = models.CharField(max_length=255)
    accel_cal_z_SENSOR_OFFSETS = models.CharField(max_length=255)
    nav_pitch_NAV_CONTROLLER_OUTPUT = models.CharField(max_length=255)
    servo3_raw_SERVO_OUTPUT_RAW = models.IntegerField()
    roll_ATTITUDE_predict = models.CharField(max_length=255)
    xgyro_RAW_IMU = models.IntegerField()
    ygyro_RAW_IMU = models.IntegerField()
    accel_cal_y_SENSOR_OFFSETS = models.CharField(max_length=255)
    zgyro_RAW_IMU = models.IntegerField()
    chan13_raw_RC_CHANNELS = models.IntegerField()
    xmag_RAW_IMU_predict = models.CharField(max_length=255)
    chan16_raw_RC_CHANNELS = models.IntegerField()





